apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: project-request
objects:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    annotations:
      openshift.io/quota-tier: Medium
    labels:
      quota-tier: Medium
    name: quota
    namespace: ${PROJECT_NAME}
  spec:
    hard:
      cpu: "2"
      memory: 12Gi
    scopes:
    - NotTerminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    annotations:
      openshift.io/quota-tier: Medium
    labels:
      quota-tier: Medium
    name: burst-quota
    namespace: ${PROJECT_NAME}
  spec:
    hard:
      cpu: "4"
      memory: 16Gi
- apiVersion: v1
  kind: LimitRange
  metadata:
    annotations:
      openshift.io/quota-tier: Medium
    labels:
      quota-tier: Medium
    name: limits
    namespace: ${PROJECT_NAME}
  spec:
    limits:
    - max:
        cpu: 200m
        memory: 2Gi
      min:
        cpu: 10m
        memory: 128Mi
      type: Pod
    - default:
        cpu: 50m
        memory: 256Mi
      max:
        cpu: 200m
        memory: 2Gi
      min:
        cpu: 20m
        memory: 256Mi
      type: Container
parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_ADMIN_USER
- name: PROJECT_REQUESTING_USER